# Recommended List


| Model                                  |  Type                                  |  Price       | Can Do                                                                                                                                                                            | Can't Do                                                                                            |  Notes                                                                                                                                                                                                                                |
|----------------------------------------|----------------------------------------|--------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Oreck XL21 (Used)                      | Bagged Upright   w/o Brushroll Switch  | $75 or less  | ❗ Hard Floors<br>     ✅ Flat Pile Rugs<br>     ✅ Low Pile Rugs<br>     ✅ Low Pile Carpet<br>     ✅ Medium Pile Carpet<br>     ✅ High Pile Carpet                                  | ❌ Above Floor Cleaning                                                                              | Lightweight and easily   serviceable but still effective at cleaning carpets. Also sold under the   model names Platinum and Elevate. No attachments, so users sometimes pair   this vacuum with a small canister.                    |
| Bissell   Zing (Bagged)                | Bagged Canister w/ Bare Floor Nozzle   | $80          | ✅ Hard   Floors<br>     ✅ Flat Pile Rugs<br>     ✅ Above Floor Cleaning                                                                                                           | ❌ Low   Pile Rugs<br>     ❌ Low Pile Carpet<br>     ❌ Medium Pile Carpet<br>     ❌ High Pile Carpet | Can be   fitted with HEPA bags and filters from Simplicity Jill                                                                                                                                                                       |
| Eureka Mighty Mite                     | Bagged Canister   w/ Bare Floor Nozzle | $80          | ✅ Hard Floors<br>     ✅ Flat Pile Rugs<br>     ✅ Above Floor Cleaning                                                                                                             | ❌ Low Pile Rugs<br>     ❌ Low Pile Carpet<br>     ❌ Medium Pile Carpet<br>     ❌ High Pile Carpet   | 3rd party HEPA bags are   available                                                                                                                                                                                                   |
| Kirby   (Used)                         | Bagged Upright w/o Brushroll Switch    | $100 or less | ✅ Flat   Pile Rugs<br>     ✅ Low Pile Rugs<br>     ✅ Low Pile Carpet<br>     ✅ Medium Pile Carpet<br>     ✅ High Pile Carpet<br>     ❗ Above Floor Cleaning                       | ❌ Hard   Floors                                                                                     | Extremely   well built vacuums that excel at cleaning carpet. Very heavy and unwieldy,   which is why people sell them cheaply. Awakward/outdated attachment hose   setup, so users sometimes pair this vacuum with a small canister. |
| Sanitaire Mighty Mite                  | Bagged Canister   w/ Bare Floor Nozzle | $150         | ✅ Hard Floors<br>     ✅ Flat Pile Rugs<br>     ✅ Above Floor Cleaning                                                                                                             | ❌ Low Pile Rugs<br>     ❌ Low Pile Carpet<br>     ❌ Medium Pile Carpet<br>     ❌ High Pile Carpet   | Eureka Mighty Mite with better   attachments                                                                                                                                                                                          |
| Simplicity   Jill                      | Bagged Canister w/ Bare Floor Nozzle   | $150         | ✅ Hard   Floors<br>     ✅ Flat Pile Rugs<br>     ✅ Above Floor Cleaning                                                                                                           | ❌ Low   Pile Rugs<br>     ❌ Low Pile Carpet<br>     ❌ Medium Pile Carpet<br>     ❌ High Pile Carpet | Fancier   version of the Bissell Zing with better quality attachments                                                                                                                                                                 |
| Hoover Complete Performance   Advanced | Bagged Upright   w/o Brushroll Switch  | $160         | ✅ Flat Pile Rugs<br>     ✅ Low Pile Rugs<br>     ✅ Low Pile Carpet<br>     ✅ Medium Pile Carpet<br>     ✅ High Pile Carpet<br>     ❗ Above Floor Cleaning                         | ❌ Hard Floors                                                                                       | Downgraded version of the Hoover   T-Series Tempo, brushroll switch has been removed                                                                                                                                                  |
| Kenmore   Intuition                    | Bagged Upright w/ Brushroll Switch     | $160         | ❗ Hard   Floors<br>     ✅ Flat Pile Rugs<br>     ✅ Low Pile Rugs<br>     ✅ Low Pile Carpet<br>     ✅ Medium Pile Carpet<br>     ✅ High Pile Carpet<br>     ❗ Above Floor Cleaning |                                                                                                     | ----                                                                                                                                                                                                                                  |
| Kenmore 200 Series                     | Bagged Canister   w/ Electric Nozzle   | $200         | ✅ Hard Floors<br>     ✅ Flat Pile Rugs<br>     ✅ Low Pile Rugs<br>     ✅ Low Pile Carpet<br>     ✅ Medium Pile Carpet<br>     ✅ High Pile Carpet<br>     ✅ Above Floor Cleaning   |                                                                                                     | ----                                                                                                                                                                                                                                  |
